// Tells input events generated by Buddy's own input driver apart from real
// user input, so the kill switch and takeover detection react only to the
// user. Pure module: no Electron imports, fully unit-testable.

export type KeyDirection = 'down' | 'up';

/** How long a recorded synthetic event can excuse an observed event. */
const KEY_WINDOW_MS = 500;

/**
 * The input driver records every key event it synthesizes; uiohook events
 * that match a recent recording are ignored. Raw text typing can't be
 * enumerated per key, so it is covered by a typing window instead.
 */
export class SyntheticKeyFilter {
  private pending: Array<{ keycode: number; direction: KeyDirection; time: number }> = [];
  private typingUntil = 0;

  constructor(private readonly windowMs = KEY_WINDOW_MS) {}

  /** The driver is about to synthesize this key event. */
  record(keycode: number, direction: KeyDirection, now: number): void {
    this.pending.push({ keycode, direction, time: now });
  }

  /** The driver is typing raw text until roughly this time. */
  markTyping(untilTime: number): void {
    this.typingUntil = Math.max(this.typingUntil, untilTime);
  }

  isTyping(now: number): boolean {
    return now < this.typingUntil;
  }

  /**
   * Was this observed (uiohook) event produced by the driver? Consumes the
   * oldest matching recording inside the window, so one recorded event only
   * excuses one observed event.
   */
  shouldIgnore(keycode: number, direction: KeyDirection, now: number): boolean {
    this.pending = this.pending.filter((event) => now - event.time <= this.windowMs);
    const index = this.pending.findIndex(
      (event) => event.keycode === keycode && event.direction === direction,
    );
    if (index === -1) return false;
    this.pending.splice(index, 1);
    return true;
  }

  reset(): void {
    this.pending = [];
    this.typingUntil = 0;
  }
}

/**
 * Watches where the agent last put the mouse; a real cursor position far from
 * there means the user grabbed the mouse. Driver-animated movements (drags)
 * are excused by an activity window.
 */
export class AgentMouseTracker {
  private last: { x: number; y: number } | null = null;
  private activeUntil = 0;

  constructor(private readonly thresholdPx = 30) {}

  recordPosition(x: number, y: number): void {
    this.last = { x, y };
  }

  /** The driver is moving the mouse itself (e.g. a drag) until this time. */
  markActivity(untilTime: number): void {
    this.activeUntil = Math.max(this.activeUntil, untilTime);
  }

  /** True when an observed mouse position means the user took over. */
  isUserMove(x: number, y: number, now: number): boolean {
    if (now < this.activeUntil || !this.last) return false;
    return Math.hypot(x - this.last.x, y - this.last.y) > this.thresholdPx;
  }

  reset(): void {
    this.last = null;
    this.activeUntil = 0;
  }
}
